---
title: Onefortheroadpodcast
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: one for the road podcast
description: podcast
avatar: 
baseurl: onefortheroadpodcast
markdown: redcarpet
highlighter: rouge
permalink: "/:title/"
version: v1.1.0
sass:
  style: :expanded
gems:
- jekyll-sitemap
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
